-- MySQL Script generated by MySQL Workbench
-- ter 10 jul 2018 15:57:12 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TIPOS_USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TIPOS_USUARIO` (
  `id_tipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_tipo_usuario`),
  UNIQUE INDEX `id_tipo_usuario_UNIQUE` (`id_tipo_usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CICLO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CICLO` (
  `id_ciclo` INT NOT NULL,
  `tipo_ciclo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_ciclo`),
  UNIQUE INDEX `id_ciclo_UNIQUE` (`id_ciclo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CURSOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CURSOS` (
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `curso_nome` VARCHAR(50) NOT NULL,
  `id_ciclo` INT NOT NULL,
  PRIMARY KEY (`id_curso`),
  UNIQUE INDEX `id_curso_UNIQUE` (`id_curso` ASC),
  INDEX `fk_CURSOS_CICLO1_idx` (`id_ciclo` ASC),
  CONSTRAINT `id_ciclo`
    FOREIGN KEY (`id_ciclo`)
    REFERENCES `mydb`.`CICLO` (`id_ciclo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USUARIOS` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `id_tipo_usuario` INT NOT NULL,
  `id_curso` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_USUARIO_TIPO_USUARIO_idx` (`id_tipo_usuario` ASC),
  INDEX `id_curso_idx` (`id_curso` ASC),
  CONSTRAINT `id_tipo_usuario`
    FOREIGN KEY (`id_tipo_usuario`)
    REFERENCES `mydb`.`TIPOS_USUARIO` (`id_tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_curso`
    FOREIGN KEY (`id_curso`)
    REFERENCES `mydb`.`CURSOS` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DISCIPLINAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DISCIPLINAS` (
  `id_disciplina` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `id_curso` INT NOT NULL,
  PRIMARY KEY (`id_disciplina`),
  UNIQUE INDEX `id_disciplina_UNIQUE` (`id_disciplina` ASC),
  INDEX `fk_DISCIPLINAS_CURSOS1_idx` (`id_curso` ASC),
  CONSTRAINT `id_curso`
    FOREIGN KEY (`id_curso`)
    REFERENCES `mydb`.`CURSOS` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`QUESTOES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`QUESTOES` (
  `id_questao` INT NOT NULL,
  `enunciado` VARCHAR(45) NOT NULL,
  `alternativa_a` VARCHAR(45) NOT NULL,
  `alternativa_b` VARCHAR(45) NOT NULL,
  `alternativa_c` VARCHAR(45) NOT NULL,
  `alternativa_d` VARCHAR(45) NOT NULL,
  `alternativa_e` VARCHAR(45) NOT NULL,
  `alternativa_correta` VARCHAR(45) NOT NULL,
  `id_disciplina` INT NOT NULL,
  PRIMARY KEY (`id_questao`),
  INDEX `fk_QUESTOES_DISCIPLINAS1_idx` (`id_disciplina` ASC),
  CONSTRAINT `id_disciplina`
    FOREIGN KEY (`id_disciplina`)
    REFERENCES `mydb`.`DISCIPLINAS` (`id_disciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SIMULADOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SIMULADOS` (
  `id_simulado` INT NOT NULL AUTO_INCREMENT,
  `descricao_simulado` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_simulado`),
  UNIQUE INDEX `id_simulado_UNIQUE` (`id_simulado` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`QUESTOES_SIMULADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`QUESTOES_SIMULADO` (
  `id_questao` INT NOT NULL,
  `id_simulado` INT NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`id_questao`, `id_simulado`),
  INDEX `id_simulado_idx` (`id_simulado` ASC),
  CONSTRAINT `id_questao`
    FOREIGN KEY (`id_questao`)
    REFERENCES `mydb`.`QUESTOES` (`id_questao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_simulado`
    FOREIGN KEY (`id_simulado`)
    REFERENCES `mydb`.`SIMULADOS` (`id_simulado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ALUNO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ALUNO` (
  `id_aluno` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `id_curso` INT NOT NULL,
  PRIMARY KEY (`id_aluno`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `id_aluno_UNIQUE` (`id_aluno` ASC),
  INDEX `fk_ALUNO_CURSOS1_idx` (`id_curso` ASC),
  CONSTRAINT `id_curso`
    FOREIGN KEY (`id_curso`)
    REFERENCES `mydb`.`CURSOS` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SIMULADO_ALUNO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SIMULADO_ALUNO` (
  `id_simulado` INT NOT NULL,
  `id_aluno` INT NOT NULL,
  `data` DATE NOT NULL,
  INDEX `fk_SIMULADO_ALUNO_SIMULADOS1_idx` (`id_simulado` ASC),
  INDEX `fk_SIMULADO_ALUNO_ALUNO1_idx` (`id_aluno` ASC),
  PRIMARY KEY (`id_simulado`, `id_aluno`),
  UNIQUE INDEX `id_simulado_UNIQUE` (`id_simulado` ASC),
  UNIQUE INDEX `id_aluno_UNIQUE` (`id_aluno` ASC),
  CONSTRAINT `id_simulado`
    FOREIGN KEY (`id_simulado`)
    REFERENCES `mydb`.`SIMULADOS` (`id_simulado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_aluno`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `mydb`.`ALUNO` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TURMA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TURMA` (
  `id_ciclo` INT NOT NULL,
  `id_aluno` INT NOT NULL,
  `data_ciclo` DATE NOT NULL,
  PRIMARY KEY (`id_ciclo`, `id_aluno`),
  INDEX `fk_TURMA_ALUNO1_idx` (`id_aluno` ASC),
  CONSTRAINT `id_aluno`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `mydb`.`ALUNO` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_ciclo`
    FOREIGN KEY (`id_ciclo`)
    REFERENCES `mydb`.`CICLO` (`id_ciclo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RESPOSTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RESPOSTA` (
  `id_questao` INT NOT NULL,
  `id_aluno` INT NOT NULL,
  `alternativa_questao` VARCHAR(3) NULL,
  INDEX `fk_RESPOSTA_QUESTOES1_idx` (`id_questao` ASC),
  PRIMARY KEY (`id_aluno`, `id_questao`),
  CONSTRAINT `id_questao`
    FOREIGN KEY (`id_questao`)
    REFERENCES `mydb`.`QUESTOES` (`id_questao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_aluno`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `mydb`.`ALUNO` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
